language: node_js

cache: npm
  # directories: 
  #   - ~!@/.npm

node_js:
 - '12'

git: 
  depth: 3

script:
  - yarn build
  - echo 'https://miurl.com' > public/CNAME

deploy: 
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on: 
    branch: develop